# PASC-H Configuration
dataset: 'Bitcoin-OTC'
# ShortcutShift
# DegreeShift
datapath: 'Data/'
log_dir: 'logs/'
seed: 1
batch_size: 3072
dim_h: 128
dim_z: 128
drop_edge_rate: 0.2
dropout: 0.2
epochs: 500
l2reg: 0.001
lr: 0.0005
patience: 30
gpu: 2
svd_rank: 128
name: 'PASC-H'
