# PASC-H Configuration
dataset: 'Epinions'
# -DegreeShift-MST
# -ShortcutShift-MST
datapath: 'Data/'
log_dir: 'logs/'
batch_size: 16384
beta: 0.02
dim_h: 128
dim_z: 128
drop_edge_rate: 0.1
dropout: 0.3
epochs: 500
l2reg: 0.0008
lr: 0.0005
patience: 30
main_loss: 'bce'
gpu: 1
svd_rank: 128
name: 'PASC-H'