dataset: 'Slashdot'
# -DegreeShift-MST
# -ShortcutShift-MST
datapath: 'Data/'
log_dir: 'logs/'
seed: 1
gpu: 3
dim_h: 128
dim_z: 128
dropout: 0.35
drop_edge_rate: 0.1
l2reg: 0.005 #0.005
epochs: 500
batch_size: 16384
patience: 30
lr: 0.0006 #0.0005
svd_rank: 128
feature_type: 'svd'
name: 'PASC-S'